name: build
on: 
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  DOTNET_NOLOGO: true
  Configuration: Release

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 🤘 checkout
        uses: actions/checkout@v2
        with: 
          submodules: recursive
          fetch-depth: 0

      - name: ⚙ msbuild
        uses: microsoft/setup-msbuild@v1.1

      - name: 🙏 build
        run: msbuild -r

      - name: 🛠 vs
        run: |
          dotnet tool install -g dotnet-vs
          vs where --prop=EnginePath >> $env:GITHUB_PATH

      - name: ⚙ vsix
        run: | 
          vs /NoSplash /ResetSettings CSharp /Command "File.Exit"
          wait-process -name 'devenv'
          vsixinstaller.exe /nr /sp /q Kzu.vsix
          wait-process -name vsixinstaller
          vs

      - name: 🧪 test
        run: | 
          dotnet test --no-build --blame-hang-timeout 5m --blame-hang-dump-type full -r ./out

      - name: ❎ vs
        run: vs kill all

      - name: 📦 artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: tests-${{ github.run_number }}
          path: ./out