name: build
on: 
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  DOTNET_NOLOGO: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 🤘 checkout
        uses: actions/checkout@v2
        with: 
          submodules: recursive
          fetch-depth: 0

      - name: ⚙ setup
        run: dotnet tool install -g dotnet-vs

      - name: ⚙ install
        run: vs where

      - name: ≥ devenv
        run: echo "$(vs where --prop=InstallationPath)\MSBuild\Current\Bin" >> $env:GITHUB_PATH

      - name: 🙏 build
        run: msbuild -r /p:Configuration=Release

      - name: 🧪 test
        run: | 
          vs /ResetSettings General /Command "File.Exit"
          wait-process -name 'devenv'
          vs
          dotnet test -c Release --no-build --blame-hang-timeout 10m --blame-hang-dump-type full --logger "console;verbosity=detailed" -r "./out"

      - name: 📦 artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: tests-${{ github.run_number }}
          path: ./out